---
- name: Install Prometheus
  hosts: all
  become: true
  gather_facts: true
  vars:
    service_identifier: "{{ prometheus.service_identifier }}"
  vars_files:
    - group_vars/all.yml
    - group_vars/default.yml
    - group_vars/vault.yml
  roles:
    - common
    - prometheus
