---
- name: Install Solana Exporter
  hosts: all
  become: true
  gather_facts: true
  vars:
    service_identifier: "{{ solana_exporter.service_identifier }}"
  vars_files:
    - group_vars/all.yml
    - group_vars/default.yml
    - group_vars/vault.yml
  roles:
    - common
    - solana_exporter
