---
- name: Install Alert Manager
  hosts: all
  become: true
  gather_facts: true
  vars:
    service_identifier: "{{ alert_manager.service_identifier }}"
  vars_files:
    - group_vars/all.yml
    - group_vars/default.yml
    - group_vars/vault.yml
  roles:
    - common
    - alert_manager
