---
- name: Install Node Exporter
  hosts: all
  become: true
  gather_facts: false
  vars:
    service_identifier: "{{ node_exporter.service_identifier }}"
  vars_files:
    - group_vars/all.yml
    - group_vars/default.yml
  roles:
    - common
    - node_exporter
